# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\x9c\xb0\xe5\x90\x8d')),
                ('code', models.CharField(max_length=255, verbose_name=b'\xe4\xbb\xa3\xe7\xa0\x81')),
                ('type', models.IntegerField(choices=[(0, b'\xe5\x9b\xbd\xe5\xae\xb6'), (1, b'\xe7\x9c\x81'), (2, b'\xe5\xb8\x82'), (3, b'\xe5\x8c\xba\xe5\x8e\xbf')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('parent', models.IntegerField(verbose_name=b'\xe7\x88\xb6\xe7\xba\xa7\xe7\xbc\x96\xe5\x8f\xb7(\xe5\x85\xb3\xe8\x81\x94\xe8\x87\xaa\xe5\xb7\xb2)')),
            ],
            options={
                'verbose_name': '\u6240\u5728\u5730',
                'verbose_name_plural': '\u6240\u5728\u5730',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('content', models.TextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('privilege', models.BooleanField(default=False)),
                ('browse_num', models.IntegerField(default=0, verbose_name=b'\xe6\xb5\x8f\xe8\xa7\x88\xe6\xac\xa1\xe6\x95\xb0')),
                ('repeat_num', models.IntegerField(default=0, verbose_name=b'\xe8\xbd\xac\xe5\x8f\x91\xe6\x95\xb0')),
                ('like_num', models.IntegerField(default=0, verbose_name=b'\xe5\x96\x9c\xe6\xac\xa2\xe6\xac\xa1\xe6\x95\xb0')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xa5\xe6\x9c\x9f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'ordering': ['-update_date'],
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('description', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7c7b\u578b',
                'verbose_name_plural': '\u6587\u7ae0\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe5\x86\x85\xe5\xae\xb9')),
                ('poll_num', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb5\x9e\xe6\x95\xb0')),
                ('tread_num', models.IntegerField(default=0, verbose_name=b'\xe8\xb8\xa9\xe6\x95\xb0')),
                ('reply_num', models.IntegerField(default=0, verbose_name=b'\xe5\x9b\x9e\xe5\xa4\x8d\xe6\x95\xb0')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe8\xa1\xa8\xe6\x97\xb6\xe9\x97\xb4')),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Comment', verbose_name=b'\xe5\x9b\x9e\xe5\xa4\x8d')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name_plural': '\u597d\u53cb\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name=b'\xe6\xb6\x88\xe6\x81\xaf')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xb6\xe9\x97\xb4')),
                ('poll_num', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe8\xb5\x9e\xe6\x95\xb0')),
                ('comment_num', models.IntegerField(default=0, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x95\xb0')),
                ('repeat_num', models.IntegerField(default=0, verbose_name=b'\xe8\xbd\xac\xe5\x8f\x91\xe6\x95\xb0')),
                ('tread_num', models.IntegerField(default=0, verbose_name=b'\xe8\xb8\xa9\xe6\x95\xb0')),
                ('browse_num', models.IntegerField(default=0, verbose_name=b'\xe6\xb5\x8f\xe8\xa7\x88\xe6\x95\xb0')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.Category', verbose_name=b'\xe6\x9d\xa5\xe6\xba\x90')),
            ],
            options={
                'verbose_name': '\u6d88\u606f',
                'verbose_name_plural': '\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\x98\x85\xe8\xaf\xbb')),
                ('type', models.IntegerField(verbose_name=b'\xe9\x80\x9a\xe7\x9f\xa5\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notice_comment', to='mvc.Comment', verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name_plural': '\u901a\u77e5',
            },
        ),
        migrations.CreateModel(
            name='PollComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifpoll', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Comment')),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Note')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u8e29',
                'verbose_name_plural': '\u8bc4\u8bba\u8e29',
            },
        ),
        migrations.CreateModel(
            name='PollNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifpoll', models.BooleanField(default=False)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Note')),
            ],
            options={
                'verbose_name': '\u6d88\u606f\u70b9\u8d5e',
                'verbose_name_plural': '\u6d88\u606f\u70b9\u8d5e',
            },
        ),
        migrations.CreateModel(
            name='TheadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifthread', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Comment')),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Note')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u8e29',
                'verbose_name_plural': '\u8bc4\u8bba\u8e29',
            },
        ),
        migrations.CreateModel(
            name='ThreadNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifthread', models.BooleanField(default=False)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Note')),
            ],
            options={
                'verbose_name': '\u6d88\u606f\u8e29',
                'verbose_name_plural': '\u6d88\u606f\u8e29',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('password', models.CharField(max_length=100, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('realname', models.CharField(blank=True, max_length=20, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email')),
                ('face', models.ImageField(blank=True, default=b'', upload_to=b'face/%Y/%m/%d', verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f')),
                ('url', models.CharField(blank=True, default=b'', max_length=200, verbose_name=b'\xe4\xb8\xaa\xe4\xba\xba\xe4\xb8\xbb\xe9\xa1\xb5')),
                ('about', models.TextField(blank=True, default=b'', max_length=1000, verbose_name=b'\xe5\x85\xb3\xe4\xba\x8e\xe6\x88\x91')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe6\x97\xb6\xe9\x97\xb4')),
                ('sex', models.CharField(blank=True, choices=[(b'0', b'\xe7\x94\xb7'), (b'1', b'\xe5\xa5\xb3')], default=b'0', max_length=1, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('friend_num', models.IntegerField(default=0, verbose_name=b'\xe5\xa5\xbd\xe5\x8f\x8b\xe6\x95\xb0')),
                ('note_num', models.IntegerField(default=0, verbose_name=b'\xe6\xb6\x88\xe6\x81\xaf\xe6\x95\xb0')),
                ('grade', models.IntegerField(default=0, verbose_name=b'\xe5\x88\x86\xe6\x95\xb0')),
                ('sign', models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe')),
                ('logger', models.TextField(blank=True, default=b'', verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97')),
                ('area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Area', verbose_name=b'\xe5\x9c\xb0\xe5\x8c\xba')),
                ('friend', models.ManyToManyField(blank=True, related_name='_user_friend_+', to='mvc.User', verbose_name=b'\xe6\x9c\x8b\xe5\x8f\x8b')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AddField(
            model_name='threadnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.User'),
        ),
        migrations.AddField(
            model_name='theadcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.User'),
        ),
        migrations.AddField(
            model_name='pollnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.User'),
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.User'),
        ),
        migrations.AddField(
            model_name='notice',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_receiver', to='mvc.User', verbose_name=b'\xe6\x8e\xa5\xe5\x8f\x97\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='notice',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_sender', to='mvc.User', verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.User', verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='mvc.User', verbose_name=b'\xe6\x8e\xa5\xe5\x8f\x97\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='mvc.User', verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.Note', verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\xb6\x88\xe6\x81\xaf'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mvc.User', verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.User', verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvc.ArticleType', verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
