# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0003_notice_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_tread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe9\x98\x85\xe8\xaf\xbb')),
                ('type', models.IntegerField(verbose_name=b'\xe9\x80\x9a\xe7\x9f\xa5\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe6\x97\xb6\xe9\x97\xb4')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_tread_receiver', to='mvc.User', verbose_name=b'\xe6\x8e\xa5\xe5\x8f\x97\xe8\x80\x85')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_tread_sender', to='mvc.User', verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe8\x80\x85')),
                ('treadNote', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mvc.ThreadNote', verbose_name=b'\xe8\xb8\xa9\xe5\xaf\xb9\xe6\x96\xb9\xe7\x9a\x84\xe6\xb6\x88\xe6\x81\xaf')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name_plural': '\u901a\u77e5',
            },
        ),
    ]
