# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0006_notice_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=60, verbose_name=b'\xe5\x88\x86\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logger',
            field=models.TextField(blank=True, default=b'', max_length=1000, verbose_name=b'\xe6\x97\xa5\xe5\xbf\x97'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign',
            field=models.CharField(blank=True, default=b'', max_length=200, verbose_name=b'\xe6\xa0\x87\xe7\xad\xbe'),
        ),
    ]
