# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0009_auto_20170630_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(default=60, verbose_name=b'\xe5\x88\x86\xe6\x95\xb0'),
        ),
    ]
