# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 22:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0010_auto_20170630_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=b'\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
